df<-read.table("household_power_consumption.txt", header=FALSE, sep=";")
d<-df[df$V1=="1/2/2007" | df$V1=="2/2/2007",]
d$V1<-as.Date(d$V1,"%d/%m/%Y")
d$V1<-format(d$V1,"%y %m %d")
head(d)
d$V2<-strptime(d$V2,format = "%H:%M:%S")
d$V2<-format(d$V2,format = "%H:%M:%S")
head(d)
require(scales) 
require(ggplot2)
d$V3<-as.numeric(as.matrix(d$V3))
d$V5<-as.numeric(as.matrix(d$V5))
d$V7<-as.numeric(as.matrix(d$V7))
d$V8<-as.numeric(as.matrix(d$V8))
d$V9<-as.numeric(as.matrix(d$V9))
d$V4<-as.numeric(as.matrix(d$V4))
d$newdate<-paste(d$V1, d$V2)
d$newdate<-strptime(d$newdate,"%y %m %d %H:%M:%S")
p1<-ggplot(d, aes(newdate, V3)) + geom_line() + xlab("") + ylab("Global Active Power (in kilowatts)") 
p2<-ggplot(d, aes(newdate, V5)) + geom_line() + xlab("") + ylab("Voltage") 

p3<-ggplot(d, aes(newdate)) +  geom_line(aes(y=V7),colour="black") +  geom_line(aes(y=V8),colour="red")  +  geom_line(aes(y=V9),colour="blue") + xlab("") + ylab("Energy Sub Metering")
p4<-ggplot(d, aes(newdate, V4)) + geom_line() + xlab("") + ylab("Global Reactive Power (in kilowatts)") 

grid.arrange(p1, p2, p3, p4, ncol = 2, top = "Main Plot")
dev.copy(png,'plot4.png')
dev.off()
